name: Super-Linter-Backend

on: push

defaults:
  run:
    working-directory: ./backend

jobs:
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 19.x
      - run: npm install
      - run: npm run lint
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}








    
